### ISSUE TITLE
Support of phpseclib/phpseclib version 2

### ISSUE THREAD

**Issue by Corn696** [civicrm/civicrm-cxn-rpc#9]
I run into some composer conflicts with other packages that require phpseclib/phpseclib in version 2.0.21

**Comment by totten** [comment]
Yeah, I think this is a good idea... let me take a quick stab and see how much it's changed...

**Comment by totten** [comment]
See #10

**Comment by HeneryH** [comment]
This old rev requirement makes CiviCRM incompatable with OpenSocial.  Trying to hack around it now.  Forking like crazy in the hope that we can just update the version without breaking anything.

**Comment by dptarrant** [comment]
Hey Tim, 

Just to add fuel to the fire... This issue also causes version conflicts when installing phpMyAdmin with CiviCRM on Drupal8, which prevents us from installing them together. Any ideas when the pull request might be merged?  (Nubay uses phpMyAdmin for client support).   Thanks

**Comment by totten** [comment]
This repo has been updated to support phpseclib 2.x in v0.20.

For vanilla Civi deployments, the next step should be a much easier bump in the dependency: https://github.com/civicrm/civicrm-core/pull/19230

In the interim, for composer-based builds which use current/older versions of civicrm-core, one could temporarily coerce the versions in the root-project's `composer.json`. Should look something like:

```javascript
"require": {
  "civicrm/civicrm-cxn-rpc": "0.20.12.01 as v0.19.01.09"
}
```
